name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Step
        run: |
            echo "Hello world"
            echo "Hello moon"
      - name: Last Step
        run: echo "Program end"
        
